---
title: "Lab 10"
author: "Erin Cagle"
format: html
editor: visual
embed-resources: true
---

## Lab 10

```{r}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

## Setup

```{r}
library(RSQLite)
library(DBI)

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
```

```{r}
dbListTables(con)
```

```{sql connection = con}
PRAGMA table_info(actor)
```

## Exercise 1

Retrieve actor ID, first name and last name from actor table.

```{sql connection=con}
SELECT actor_id, first_name, last_name
FROM actor
ORDER by last_name, first_name
```

## Exercise 2

```{sql connection= con}
SELECT actor_id, first_name, last_name
FROM actor
WHERE last_name IN ('WILLIAMS', 'DAVIS')
```

## Exercise 3

```{sql connection= con}
SELECT DISTINCT customer_id
FROM rental
WHERE date(rental_date) = '2005-07-05'
```

## Exercise 4

4.1

```{sql connection= con}
SELECT *
FROM payment
WHERE amount IN (1.99, 7.99, 9.99)
```

4.2

```{sql connection=con}
SELECT *
FROM payment
WHERE amount > 5
```

4.3

```{sql connection=con}
SELECT *
FROM payment
WHERE amount > 5 and amount < 8
```

## Exercise 5

```{sql connection=con}
SELECT payment.payment_id, payment.amount, customer.last_name
FROM payment
  INNER JOIN customer 
WHERE payment.customer_id = customer.customer_id AND customer.last_name = 'DAVIS'
```

## Exercise 6

6.1

```{sql connection=con}
SELECT COUNT(*)
FROM rental
```

6.2

```{sql connection=con}
SELECT customer_id, COUNT(*) as count
FROM rental
GROUP BY customer_id
```

6.3

```{sql connection=con}
SELECT customer_id, COUNT(*) as count
FROM rental
GROUP BY customer_id
ORDER BY count DESC
```

6.4

```{sql connection=con}
SELECT customer_id, COUNT(*) as count
FROM rental
GROUP BY customer_id
HAVING count > 40
ORDER BY count DESC
```

## Exercise 7

```{sql connection=con}
SELECT MIN(amount) as Min, MAX(amount) as Max, AVG(amount) as Avg, SUM(amount) as Sum
FROM payment
```

7.1

```{sql connection=con}
SELECT customer_id, MIN(amount) as Min, MAX(amount) as Max, AVG(amount) as Avg, SUM(amount) as Sum
FROM payment
GROUP BY customer_id

```

7.2

```{sql connection=con}
SELECT customer_id, MIN(amount) as Min, MAX(amount) as Max, AVG(amount) as Avg, SUM(amount) as Sum, COUNT(amount) as count
FROM payment
GROUP BY customer_id
HAVING count > 5
```

## Cleanup

```{r}
# clean up
dbDisconnect(con)
```
